export const mockProducts = [
  {
    sku: 'sku1',
    shopId: '4512',
    name: 'Brownie Fantasy',
    price: 69,
    mrp: 79,
    rating: 4.2,
    image: require('../../../assets/images/bg_1.png'),
    category: 'scoops',
    options: 2,
  },
  {
    sku: 'sku2',
    shopId: '4512',
    name: 'Strawberry Dream',
    price: 75,
    mrp: 85,
    rating: 4.3,
    image: require('../../../assets/images/bg_1.png'),
    category: 'scoops',
    options: 1,
  },
  {
    sku: 'sku3',
    shopId: '4512',
    name: 'Vanilla Bliss',
    price: 65,
    mrp: 75,
    rating: 4.1,
    image: require('../../../assets/images/bg_1.png'),
    category: 'scoops',
    options: 0,
  },
  {
    sku: 'sku4',
    shopId: '4512',
    name: 'Choco Sundae',
    price: 99,
    mrp: 120,
    rating: 4.5,
    image: require('../../../assets/images/bg_1.png'),
    category: 'sundaes',
    options: 0,
  },
  {
    sku: 'sku5',
    shopId: '4512',
    name: 'Nutty Sundae',
    price: 110,
    mrp: 130,
    rating: 4.6,
    image: require('../../../assets/images/bg_1.png'),
    category: 'sundaes',
    options: 1,
  },
  {
    sku: 'sku6',
    shopId: '4512',
    name: 'Mango Magic Sundae',
    price: 105,
    mrp: 120,
    rating: 4.4,
    image: require('../../../assets/images/bg_1.png'),
    category: 'sundaes',
    options: 0,
  },
  {
    sku: 'sku7',
    shopId: '4512',
    name: 'Classic Cone',
    price: 49,
    mrp: 59,
    rating: 4.0,
    image: require('../../../assets/images/bg_1.png'),
    category: 'cones',
    options: 0,
  },
  {
    sku: 'sku8',
    shopId: '4512',
    name: 'Chocolate Cone',
    price: 55,
    mrp: 65,
    rating: 4.2,
    image: require('../../../assets/images/bg_1.png'),
    category: 'cones',
    options: 0,
  },
  {
    sku: 'sku9',
    shopId: '4512',
    name: 'Rainbow Cone',
    price: 60,
    mrp: 70,
    rating: 4.0,
    image: require('../../../assets/images/bg_1.png'),
    category: 'cones',
    options: 1,
  },
  {
    sku: 'sku10',
    shopId: '4512',
    name: 'Family Delight',
    price: 299,
    mrp: 349,
    rating: 4.7,
    image: require('../../../assets/images/bg_1.png'),
    category: 'family',
    options: 0,
  },
  {
    sku: 'sku11',
    shopId: '4512',
    name: 'Party Pack',
    price: 399,
    mrp: 450,
    rating: 4.8,
    image: require('../../../assets/images/bg_1.png'),
    category: 'family',
    options: 2,
  },
  {
    sku: 'sku12',
    shopId: '4512',
    name: 'Super Saver Family',
    price: 349,
    mrp: 399,
    rating: 4.5,
    image: require('../../../assets/images/bg_1.png'),
    category: 'family',
    options: 1,
  },
  {
    sku: 'sku13',
    shopId: '4512',
    name: 'Schezwan Rice',
    price: 69,
    mrp: 79,
    rating: 4.3,
    image: require('../../../assets/images/bg_1.png'),
    category: 'scoops',
    options: 0,
  },
  {
    sku: 'sku14',
    shopId: '4512',
    name: 'Paneer Tikka Cone',
    price: 70,
    mrp: 80,
    rating: 4.2,
    image: require('../../../assets/images/bg_1.png'),
    category: 'cones',
    options: 1,
  },
  // Add more unique products as needed...
  {
    sku: 'sku15',
    shopId: '4512',
    name: 'Paneer Tikka Cone',
    price: 70,
    mrp: 80,
    rating: 4.2,
    image: require('../../../assets/images/bg_1.png'),
    category: 'scoops',
    options: 1,
  },
  {
    sku: 'sku16',
    shopId: '4512',
    name: 'Paneer Tikka Cone',
    price: 70,
    mrp: 80,
    rating: 4.2,
    image: require('../../../assets/images/bg_1.png'),
    category: 'scoops',
    options: 1,
  },
  {
    sku: 'sku17',
    shopId: '4512',
    name: 'Paneer Tikka Cone',
    price: 70,
    mrp: 80,
    rating: 4.2,
    image: require('../../../assets/images/bg_1.png'),
    category: 'scoops',
    options: 1,
  },
  {
    sku: 'sku18',
    shopId: '4512',
    name: 'Paneer Tikka Cone',
    price: 70,
    mrp: 80,
    rating: 4.2,
    image: require('../../../assets/images/bg_1.png'),
    category: 'scoops',
    options: 1,
  },
  {
    sku: 'sku19',
    shopId: '4512',
    name: 'Paneer Tikka Cone',
    price: 70,
    mrp: 80,
    rating: 4.2,
    image: require('../../../assets/images/bg_1.png'),
    category: 'scoops',
    options: 1,
  },
  {
    sku: 'sku20',
    shopId: '4512',
    name: 'Paneer Tikka Cone',
    price: 70,
    mrp: 80,
    rating: 4.2,
    image: require('../../../assets/images/bg_1.png'),
    category: 'scoops',
    options: 1,
  },
  {
    sku: 'sku21',
    shopId: '4512',
    name: 'Paneer Tikka Cone',
    price: 70,
    mrp: 80,
    rating: 4.2,
    image: require('../../../assets/images/bg_1.png'),
    category: 'scoops',
    options: 1,
  },
  {
    sku: 'sku22',
    shopId: '4512',
    name: 'Paneer Tikka Cone',
    price: 70,
    mrp: 80,
    rating: 4.2,
    image: require('../../../assets/images/bg_1.png'),
    category: 'scoops',
    options: 1,
  },
  {
    sku: 'sku23',
    shopId: '4512',
    name: 'Paneer Tikka Cone',
    price: 70,
    mrp: 80,
    rating: 4.2,
    image: require('../../../assets/images/bg_1.png'),
    category: 'scoops',
    options: 1,
  },
  {
    sku: 'sku24',
    shopId: '4512',
    name: 'Paneer Tikka Cone',
    price: 70,
    mrp: 80,
    rating: 4.2,
    image: require('../../../assets/images/bg_1.png'),
    category: 'scoops',
    options: 1,
  },
  {
    sku: 'sku25',
    shopId: '4512',
    name: 'Paneer Tikka Cone',
    price: 70,
    mrp: 80,
    rating: 4.2,
    image: require('../../../assets/images/bg_1.png'),
    category: 'scoops',
    options: 1,
  },
  {
    sku: 'sku26',
    shopId: '4512',
    name: 'Paneer Tikka Cone',
    price: 70,
    mrp: 80,
    rating: 4.2,
    image: require('../../../assets/images/bg_1.png'),
    category: 'scoops',
    options: 1,
  },
  {
    sku: 'sku27',
    shopId: '4512',
    name: 'Paneer Tikka Cone',
    price: 70,
    mrp: 80,
    rating: 4.2,
    image: require('../../../assets/images/bg_1.png'),
    category: 'scoops',
    options: 1,
  },
  {
    sku: 'sku28',
    shopId: '4512',
    name: 'Paneer Tikka Cone',
    price: 70,
    mrp: 80,
    rating: 4.2,
    image: require('../../../assets/images/bg_1.png'),
    category: 'scoops',
    options: 1,
  },
  {
    sku: 'sku29',
    shopId: '4512',
    name: 'Paneer Tikka Cone',
    price: 70,
    mrp: 80,
    rating: 4.2,
    image: require('../../../assets/images/bg_1.png'),
    category: 'scoops',
    options: 1,
  },
  {
    sku: 'sku30',
    shopId: '4512',
    name: 'Paneer Tikka Cone',
    price: 70,
    mrp: 80,
    rating: 4.2,
    image: require('../../../assets/images/bg_1.png'),
    category: 'scoops',
    options: 1,
  },
  {
    sku: 'sku31',
    shopId: '4512',
    name: 'Paneer Tikka Cone',
    price: 70,
    mrp: 80,
    rating: 4.2,
    image: require('../../../assets/images/bg_1.png'),
    category: 'scoops',
    options: 1,
  },
];
