export const mockProducts = [
  {
    id: '1',
    name: 'Brownie Fantasy',
    price: 69,
    mrp: 79,
    rating: 4.2,
    image: require('../../../assets/images/bg_1.png'),
    category: 'scoops',
    options: 2,
  },
  {
    id: '2',
    name: 'Strawberry Dream',
    price: 75,
    mrp: 85,
    rating: 4.3,
    image: require('../../../assets/images/bg_1.png'),
    category: 'scoops',
    options: 1,
  },
  {
    id: '3',
    name: 'Vanilla Bliss',
    price: 65,
    mrp: 75,
    rating: 4.1,
    image: require('../../../assets/images/bg_1.png'),
    category: 'scoops',
    options: 0,
  },
  {
    id: '4',
    name: 'Choco Sundae',
    price: 99,
    mrp: 120,
    rating: 4.5,
    image: require('../../../assets/images/bg_1.png'),
    category: 'sundaes',
    options: 0,
  },
  {
    id: '5',
    name: 'Nutty Sundae',
    price: 110,
    mrp: 130,
    rating: 4.6,
    image: require('../../../assets/images/bg_1.png'),
    category: 'sundaes',
    options: 1,
  },
  {
    id: '6',
    name: 'Mango Magic Sundae',
    price: 105,
    mrp: 120,
    rating: 4.4,
    image: require('../../../assets/images/bg_1.png'),
    category: 'sundaes',
    options: 0,
  },
  {
    id: '7',
    name: 'Classic Cone',
    price: 49,
    mrp: 59,
    rating: 4.0,
    image: require('../../../assets/images/bg_1.png'),
    category: 'cones',
    options: 0,
  },
  {
    id: '8',
    name: 'Chocolate Cone',
    price: 55,
    mrp: 65,
    rating: 4.2,
    image: require('../../../assets/images/bg_1.png'),
    category: 'cones',
    options: 0,
  },
  {
    id: '9',
    name: 'Rainbow Cone',
    price: 60,
    mrp: 70,
    rating: 4.0,
    image: require('../../../assets/images/bg_1.png'),
    category: 'cones',
    options: 1,
  },
  {
    id: '10',
    name: 'Family Delight',
    price: 299,
    mrp: 349,
    rating: 4.7,
    image: require('../../../assets/images/bg_1.png'),
    category: 'family',
    options: 0,
  },
  {
    id: '11',
    name: 'Party Pack',
    price: 399,
    mrp: 450,
    rating: 4.8,
    image: require('../../../assets/images/bg_1.png'),
    category: 'family',
    options: 2,
  },
  {
    id: '12',
    name: 'Super Saver Family',
    price: 349,
    mrp: 399,
    rating: 4.5,
    image: require('../../../assets/images/bg_1.png'),
    category: 'family',
    options: 1,
  },
  {
    id: '13',
    name: 'Schezwan Rice',
    price: 69,
    mrp: 79,
    rating: 4.3,
    image: require('../../../assets/images/bg_1.png'),
    category: 'scoops',
    options: 0,
  },
  {
    id: '14',
    name: 'Paneer Tikka Cone',
    price: 70,
    mrp: 80,
    rating: 4.2,
    image: require('../../../assets/images/bg_1.png'),
    category: 'cones',
    options: 1,
  },
  // Add more unique products as needed...
  {
    id: '15',
    name: 'Paneer Tikka Cone',
    price: 70,
    mrp: 80,
    rating: 4.2,
    image: require('../../../assets/images/bg_1.png'),
    category: 'scoops',
    options: 1,
  },
  {
    id: '16',
    name: 'Paneer Tikka Cone',
    price: 70,
    mrp: 80,
    rating: 4.2,
    image: require('../../../assets/images/bg_1.png'),
    category: 'scoops',
    options: 1,
  },
  {
    id: '17',
    name: 'Paneer Tikka Cone',
    price: 70,
    mrp: 80,
    rating: 4.2,
    image: require('../../../assets/images/bg_1.png'),
    category: 'scoops',
    options: 1,
  },
  {
    id: '18',
    name: 'Paneer Tikka Cone',
    price: 70,
    mrp: 80,
    rating: 4.2,
    image: require('../../../assets/images/bg_1.png'),
    category: 'scoops',
    options: 1,
  },
  {
    id: '19',
    name: 'Paneer Tikka Cone',
    price: 70,
    mrp: 80,
    rating: 4.2,
    image: require('../../../assets/images/bg_1.png'),
    category: 'scoops',
    options: 1,
  },
  {
    id: '20',
    name: 'Paneer Tikka Cone',
    price: 70,
    mrp: 80,
    rating: 4.2,
    image: require('../../../assets/images/bg_1.png'),
    category: 'scoops',
    options: 1,
  },
  {
    id: '15',
    name: 'Paneer Tikka Cone',
    price: 70,
    mrp: 80,
    rating: 4.2,
    image: require('../../../assets/images/bg_1.png'),
    category: 'scoops',
    options: 1,
  },
  {
    id: '21',
    name: 'Paneer Tikka Cone',
    price: 70,
    mrp: 80,
    rating: 4.2,
    image: require('../../../assets/images/bg_1.png'),
    category: 'scoops',
    options: 1,
  },
  {
    id: '22',
    name: 'Paneer Tikka Cone',
    price: 70,
    mrp: 80,
    rating: 4.2,
    image: require('../../../assets/images/bg_1.png'),
    category: 'scoops',
    options: 1,
  },
  {
    id: '15',
    name: 'Paneer Tikka Cone',
    price: 70,
    mrp: 80,
    rating: 4.2,
    image: require('../../../assets/images/bg_1.png'),
    category: 'scoops',
    options: 1,
  },
  {
    id: '23',
    name: 'Paneer Tikka Cone',
    price: 70,
    mrp: 80,
    rating: 4.2,
    image: require('../../../assets/images/bg_1.png'),
    category: 'scoops',
    options: 1,
  },
  {
    id: '24',
    name: 'Paneer Tikka Cone',
    price: 70,
    mrp: 80,
    rating: 4.2,
    image: require('../../../assets/images/bg_1.png'),
    category: 'scoops',
    options: 1,
  },
  {
    id: '25',
    name: 'Paneer Tikka Cone',
    price: 70,
    mrp: 80,
    rating: 4.2,
    image: require('../../../assets/images/bg_1.png'),
    category: 'scoops',
    options: 1,
  },
  {
    id: '26',
    name: 'Paneer Tikka Cone',
    price: 70,
    mrp: 80,
    rating: 4.2,
    image: require('../../../assets/images/bg_1.png'),
    category: 'scoops',
    options: 1,
  },
  {
    id: '15',
    name: 'Paneer Tikka Cone',
    price: 70,
    mrp: 80,
    rating: 4.2,
    image: require('../../../assets/images/bg_1.png'),
    category: 'scoops',
    options: 1,
  },
  {
    id: '27',
    name: 'Paneer Tikka Cone',
    price: 70,
    mrp: 80,
    rating: 4.2,
    image: require('../../../assets/images/bg_1.png'),
    category: 'scoops',
    options: 1,
  },
  {
    id: '28',
    name: 'Paneer Tikka Cone',
    price: 70,
    mrp: 80,
    rating: 4.2,
    image: require('../../../assets/images/bg_1.png'),
    category: 'scoops',
    options: 1,
  },
  {
    id: '29',
    name: 'Paneer Tikka Cone',
    price: 70,
    mrp: 80,
    rating: 4.2,
    image: require('../../../assets/images/bg_1.png'),
    category: 'scoops',
    options: 1,
  },
  {
    id: '30',
    name: 'Paneer Tikka Cone',
    price: 70,
    mrp: 80,
    rating: 4.2,
    image: require('../../../assets/images/bg_1.png'),
    category: 'scoops',
    options: 1,
  },
  {
    id: '31',
    name: 'Paneer Tikka Cone',
    price: 70,
    mrp: 80,
    rating: 4.2,
    image: require('../../../assets/images/bg_1.png'),
    category: 'scoops',
    options: 1,
  },
];
