def node_require(script)
  # Resolve script with node to allow for hoisting
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
      {paths: [process.argv[1]]},
    )", __dir__]).strip
end

# Require react-native and react-native-permissions scripts
node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

platform :ios, min_ios_version_supported
prepare_react_native_project!

# Enable global modular headers (Required for Firebase & react-native-permissions)
use_modular_headers!

# Enable only the permissions you actually use
setup_permissions([
  'LocationWhenInUse',
  'Notifications',
  'PhotoLibrary',
  'Camera'
])

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'qvuserapp_ui' do
  config = use_native_modules!

  # Firebase Pods (Modular headers are now handled globally by use_modular_headers!)
  pod 'Firebase'
  pod 'FirebaseCoreInternal'
  pod 'GoogleUtilities'
  pod 'FirebaseCore'
  pod 'FirebaseMessaging'

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
  react_native_post_install(
    installer,
    config[:reactNativePath],
    :mac_catalyst_enabled => false
  )

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Force allow non-modular includes across ALL framework pods (Fixes -Werror=non-modular-include-in-framework-module)
      config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
      config.build_settings['CLANG_WARN_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'NO'
      config.build_settings['DEFINES_MODULE'] = 'YES'
    end
  end
end
end
